# Generated by Django 3.0.6 on 2020-05-25 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hi',
            new_name='purpose',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='purpose_desc',
        ),
        migrations.AddField(
            model_name='post',
            name='travel_type',
            field=models.CharField(default='hh', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='cert_recieved',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 22, 35, 6, 776762), verbose_name='date recieved'),
        ),
    ]
