# Generated by Django 3.0.6 on 2020-05-25 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200525_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='cert_recieved',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 23, 43, 28, 567722), verbose_name='date recieved'),
        ),
    ]
