# Generated by Django 3.0.6 on 2020-05-25 18:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200525_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='advance_req',
            field=models.CharField(default='ws', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='air_train',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='booking_type',
            field=models.CharField(default='ee', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='classs',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='etd',
            field=models.CharField(default='errf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='from_place',
            field=models.CharField(default='erf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='journey_type',
            field=models.CharField(default='iur', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='mode',
            field=models.CharField(default='rfu', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='to_place',
            field=models.CharField(default='rf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='travel_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='cert_recieved',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 0, 18, 54, 875762), verbose_name='date recieved'),
        ),
    ]
