# Generated by Django 3.0.6 on 2020-05-26 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200526_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='cert_recieved',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 12, 7, 31, 309046), verbose_name='date recieved'),
        ),
        migrations.AlterField(
            model_name='post',
            name='travel_date',
            field=models.DateField(max_length=50),
        ),
    ]
