# Generated by Django 3.0.6 on 2020-05-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200526_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
